### ISSUE TITLE
getIncludes on HasOne and BelongsTo associations forces required true

### ISSUE THREAD

**Issue by Shinlun** [ForestAdmin/forest-express-sequelize#11]
I noticed that all queries generated in the dashboard when listing resources were made using `INNER JOIN` and not `LEFT JOIN`. Looking for an explanation for this behavior, I noticed that the `getIncludes` method in the `resources-getter` was forcing `required: true` on `HasOne` and `BelongsTo` associations, which is not sequelize default behavior.
Say we're using `HasOne` / `BelongsTo` associations to describe foreign keys that can be null (`player.belongsTo(team)`, `team_id` can be `null` if player does not have a team currently). We still need to visualize all the resources. We currently can't unless we remove that `required: true` from the module source code.
Is there a reason why you're forcing this behavior ? Could you possibly make this a custom parameter so that we can decide wether we want `INNER JOIN` or `LEFT JOIN` ?

**Comment by VinzGhyz** [comment]
Thanks for the feedback and for taking the time to draw such a complete report Shinlun! Your issue makes sense to me, but I am not the most knowledgeable regarding this particular topic so I cannot provide you with a satisfying answer at this point. Our go-to guys for this particular point are taking some well deserved time off, and will respond as soon as they get back (early next week).

**Comment by arnaudbesnier** [comment]
Hey @Shinlun,

This issue is fixed.
FYI, the package now use `LEFT OUTER JOINS` since several months.
I will close the issue, don't hesitate to reopen it if necessary.

Thanks
