### ISSUE TITLE
Can't do a combination of AND and OR operators in Segment

### ISSUE THREAD

**Issue by stemmlerjs** [ForestAdmin/forest-express-sequelize#115]
Is there a way to use AND and OR operators in a Segment?

I want to create a Segment called Unverified Students where
- (is_email_verified is 0 OR is_profile_complete is 0) AND is_a_student is 1

Every time that I click on one of the AND/OR buttons in this setup to change it, they both change.
Wondering if this is possible.

![image](https://user-images.githubusercontent.com/6892666/28757686-78070792-7556-11e7-8fe3-c292873868b6.png)

**Comment by arnaudbesnier** [comment]
Hi @stemmlerjs, you can't do that right now in the Forest interface.
But what you can do is implement a Smart Segment to bypass this.
See the following documentation: http://doc.forestadmin.com/developers-guide/#creating-a-smart-segment

🌲🌲🌲

**Comment by risonsimon** [comment]
I'm not able to get the smart segments to work.

I created a project using `lumber` which displays all the data properly in `forestadmin`.

I have a table called `deals` for which I want to create a smart segment.

This is what I have, I'm retrieving all the deals in this smart segment for testing.

```js
Liana.collection('deals', {
  segments: [{
    name: 'dealsegment',
    where: () => {
      Deals.findAll({
        attributes: ['id']
      })
    }
  }]
});
```

However, I don't see it in the `forestadmin` UI. What am I doing wrong? And is there some way to debug these errors?

I have done the following:
- restarted node server multiple times
- deleted all application data from browser and logged in again

I'm still not able to view the segments.

**Comment by arnaudbesnier** [comment]
Hi @risonsimon, sorry for the documentation that is not clear enough.

What the `where` method is supposed to return is something like:
```javascript
return { id: { $in: [1, 2, 3, 4] }};
```

You can also find a complete example here: https://gist.github.com/arnaudbesnier/2e45b0563f201e3082d2465d07dde2ad

I hope it will help!

**Comment by risonsimon** [comment]
Hi @arnaudbesnier, thanks for the quick response.

For future reference, this made it work.

```js
const _ = require('lodash');

Liana.collection('deals', {
  segments: [{
    name: 'dealsegment',
    where: () => {
      const query = 'SELECT DISTINCT(deals.id) FROM deals';

      return models.sequelize
        .query(query)
        .then((deals) => {
          return { id: { $in: _.map(deals[0], 'id') }};
        });
    }
  }]
});
```

**Comment by risonsimon** [comment]
@arnaudbesnier it worked for sometime and now the segment has disappeared.

This is the code that I'm using.

```js
'use strict';
const Liana = require('forest-express-sequelize');
const models = require('../models');
const _ = require('lodash');

Liana.collection('deals', {
  segments: [{
    name: 'dealsegment',
    where: () => {
      const query = 'SELECT DISTINCT(deals.id) FROM deals';

      return models.sequelize
        .query(query)
        .then((deals) => {
          return { id: { $in: _.map(deals[0], 'id') }};
        });
    }
  }]
});
```

Also, I'm noticing a lag between when I update the code and when it is reflected in the UI.
