### ISSUE TITLE
Does not work when deployed on AWS Lambda (serverless framework)

### ISSUE THREAD

**Issue by hammadzz** [ForestAdmin/forest-express-sequelize#117]
It works when running it locally. Tried deploying it on serverless (AWS Api Gateway + Lambda) but app.forestadmin.com console is not able to connect to it. I checked the environment variables which were initially wrong and logging errors. Now that is fixed but not getting anywhere with it.

The error I get when trying to setup forest on app.forestadmin.com:
"Forest did not received your apimap to finalize the deployment. Please, double-check that you set the correct FOREST_ENV_SECRET environment variable and then restart your production server."

1. How can I debug this? Manually see if the rest api returns apimap?
2. How is the Authorization Bearer token generated so I can try the auto-generated rest API endpoints (they seem accessible but my token is invalid)?

**Comment by arnaudbesnier** [comment]
Hi @hammadzz, I don't know how AWS Lambda works but it seems that your remote server does not send the `apimap` to Forest. Technically, it is send everytime your server starts (or restarts).
Did you restart your serverless instance once the code deployed?

**Comment by hammadzz** [comment]
@arnaudbesnier yes the container technically restarts every redeploy. Also if it has been sitting idle for 15 minutes. I know forest was trying to connect in lambda because when the secrets were wrong it would log errors. Now that the secrets are correct it is no longer doing so.

**Comment by arnaudbesnier** [comment]
@hammadzz reading this https://github.com/awslabs/aws-serverless-express#is-aws-serverless-right-for-my-app I am wondering if AWS Lambda can be used with Forest.

Do you have some start logs with this service? If yes, could you share it here?

Thanks

**Comment by arnaudbesnier** [comment]
hi @hammadzz, do you still have the issue?

**Comment by arnaudbesnier** [comment]
No news about this issue, feel free to re-open it if the problem persists.
