### ISSUE TITLE
I am not able to see model changes in the Admin UI 

### ISSUE THREAD

**Issue by angelstoone** [ForestAdmin/forest-express-sequelize#119]
Hi guys,

First of all, I really love what you are doing with the **ForestAdmin** app ❤️🌲 and thank you even for giving us the opportunity to use it for free. 

I have just one question for you. I have generated the Admin using **Lumber**🌲, and everything went smoothly. Then I have added some new fields in some DB tables and lastly, I have updated the sequelize models in order to see the new fields in the Admin but I am not able to see any changes.

I have even added a smart field and it seems that the code is computing my code but it is not showing anything. Is there a way to force the client side to refresh based on the model changes?

This should be related to #62.

**Comment by angelstoone** [comment]
The workaround for this problem for me was creating a new project on Forest Admin, then put the new credentials in the project code. Then I have restarted the express app and at the beginning, the admin UI was broken, but after ~ 10-15 minutes everything was working fine, and I was able to see the new fields as well.

**Comment by arnaudbesnier** [comment]
@angelstoone thanks for the feedback.

Are you sure this is related to #62 ? Did you have broken UI?

You should not have to do a workaround for that, the steps you described in you first comment are supposed to trigger the changes in your Admin UI (if you restarted you server after that).
Are your sure that the new fields your declared in your Sequelize models were well declared?

It can obviously be a bug in our "UI updater". We have already planed to work on its stability during our upcoming sprints.

**Comment by arnaudbesnier** [comment]
@angelstoone do you still have to do the workaround you described?
We didn't have any news about this issue so we were wondering if we can we close the issue.
