### ISSUE TITLE
ID created as '[object Object]'

### ISSUE THREAD

**Issue by jtl3d** [ForestAdmin/forest-express-sequelize#121]
I'm not sure why but when adding new records via the ForestAdmin interface, the ID field on my models is autogenerated as '[object Object]'. This also leads to me not being able to add any new records after adding one since they would have the same ID. My models are defined with the ID fields being DataType.UUID.

Any idea what is wrong?

**Comment by arnaudbesnier** [comment]
Hi @jtl3d, Forest is supposed to support UUID properly.
Can you provide us your model declaration (or at least the ID declaration if you don't want to share the whole model)? It would help us a lot to try to reproduce your issue.

Thank you!

**Comment by jtl3d** [comment]
Yeah it was working up until a few days ago, so I'm stumped. Here is an example of one of my models - it happens for all models though:
```
const Network = Model.define('Network', {
  id: {
    type: DataType.UUID,
    defaultValue: DataType.UUIDV1,
    primaryKey: true,
  },
  name: {
    type: DataType.ENUM(
      'foo',
      'bar',
      'baz',
    ),
  },
  description: {
    type: DataType.STRING(255),
  },
  isActive: {
    type: DataType.BOOLEAN,
    defaultValue: true,
  },
  image: {
    type: DataType.STRING(255),
  },
});
```

**Comment by jtl3d** [comment]
@arnaudbesnier Any ideas?

**Comment by arnaudbesnier** [comment]
@jtl3d Your model seems ok. Can you send me the payload of the creation request sent by the browser (in the network tab of the developer console).
I want to see if the record id is generated by the browser UI or if it is the back-end that contain the issue.

Thanks!

**Comment by arnaudbesnier** [comment]
@jtl3d, I just reproduced your issue. It is an issue with the "default values" features we shipped a few weeks ago.

We will fix this issue this week for sure.
I'll let you know.

Thank you for the report!

**Comment by jtl3d** [comment]
@arnaudbesnier Oh great! Thanks!

**Comment by arnaudbesnier** [comment]
@jtl3d you can upgrade to the latest liana version (1.2.0) to fix the issue

**Comment by jtl3d** [comment]
@arnaudbesnier Thanks! It's working now!
