### ISSUE TITLE
Unexpected error in the list view:  TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by jtl3d** [ForestAdmin/forest-express-sequelize#138]
I'm not sure why some of my tables are doing this, but this is the error in the console when I try to load the data.

```
vendor-70f3d283c05843483820f9adb8823679.js:112 [forest] 🌳🌳🌳 Unexpected error in the list view:  TypeError: Cannot read property 'type' of null
    at r._pushInternalModel (vendor-70f3d283c05843483820f9adb8823679.js:119)
    at vendor-70f3d283c05843483820f9adb8823679.js:119
    at d.run (vendor-70f3d283c05843483820f9adb8823679.js:7)
    at d.join (vendor-70f3d283c05843483820f9adb8823679.js:7)
    at r._push (vendor-70f3d283c05843483820f9adb8823679.js:119)
    at vendor-70f3d283c05843483820f9adb8823679.js:119
    at A (vendor-70f3d283c05843483820f9adb8823679.js:23)
    at k (vendor-70f3d283c05843483820f9adb8823679.js:23)
    at C (vendor-70f3d283c05843483820f9adb8823679.js:23)
    at invokeWithOnError (vendor-70f3d283c05843483820f9adb8823679.js:7)
```

I see the data that was loaded and type is referenced. Here is a snippet:

```
{  
   "meta":{  
      "count":5
   },
   "data":[  
      {  
         "type":"faq-section",
         "id":"a9b9b870-a3d2-11e7-88c1-91b093414a29",
         "attributes":{  
            "id":"a9b9b870-a3d2-11e7-88c1-91b093414a29",
            "section":"Basics",
            "order":1,
            "createdAt":"2017-09-28T02:06:29.000Z",
            "updatedAt":"2017-09-28T02:06:29.000Z"
         },
         "relationships":{  
            "faqs":{  
               "links":{  
                  "related":{  
                     "href":"/forest/FAQSection/a9b9b870-a3d2-11e7-88c1-91b093414a29/relationships/faqs"
                  }
               }
            }
         }
      },
      ...
```

Here's that object:

```
const FAQSection = Model.define('FAQSection', {
  id: {
    type: DataType.UUID,
    defaultValue: DataType.UUIDV1,
    primaryKey: true,
  },
  section: {
    type: DataType.STRING(120),
  },
  order: {
    type: DataType.INTEGER,
  },
});
```

And the relationship:

```
FAQSection.FAQ = FAQSection.hasMany(FAQ, {
  foreignKey: 'faqSectionId',
  as: 'faqs',
  onUpdate: 'cascade',
  onDelete: 'cascade'
});
```

Let me know what else info you need to track this down.

**Comment by arnaudbesnier** [comment]
Hi @jtl3d, thank you for the report!

I feel like this is a Forest issue with some of your collections having names with specific case.
Can you list here, along with `FAQSection`, the other collections you cannot display in Forest?

Thanks for helping us.

**Comment by jtl3d** [comment]
I think you're on to something:

CJAffiliateTransactions
FAQSection
FAQs
ShareASaleTransactions

These all have at least two capital letters in a row. The rest don't, and load fine.

**Comment by jtl3d** [comment]
Looking through the code I notice `_.capitalize` is used sometimes, and `.type` is in a few places, but maybe `getTypeFor()` is the culprit? There is a check for `column.type.type` which could throw if `column.type` is undefined. I'm just shooting in the dark here.

**Comment by juliocanares** [comment]
@arnaudbesnier are you guys already working on this issue? I'd like to help.

**Comment by juliocanares** [comment]
changing `_.capitalize` by` _.upperFirst` should do the work.

**Comment by arnaudbesnier** [comment]
@jtl3d @juliocanares this is something we have to work on.
This is a global issue of names handling. We have to handle model name cases like:
`be_RightRoles`,  `CMMicrositeUser`, `ELMAH_Error`, `_User`, `ACHCredit`, and so on

It could be one of the priorities for next sprint.

**Comment by jtl3d** [comment]
@arnaudbesnier looks like the related prs that could potentially fix this are about ready to be merged - what is the eta for that to happen?

**Comment by arnaudbesnier** [comment]
hey @jtl3d as this is something really sensitive, we'd like to take the time to release this without taking any risks of regression.
I think it should be released before the end of next week.

**Comment by greatbody** [comment]
I met this issue hours ago

I have a table named "i18n"

and its' model generated by your tool is 
```javascript
'use strict';

module.exports = (sequelize, DataTypes) => {
  var Model = sequelize.define('i18n', {
    id: {
      type: DataTypes.BIGINT,
      defaultValue: "nextval('i18n_id_seq')",
      allowNull: false,
      primaryKey: true
    },
  }, {
    tableName: 'i18n',
    underscored: false,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  Model.associate = (models) => {
  };

  return Model;
};

```

and I have the same problem with the owner of this issue,

The way I fix this:
change the :sequelize.define('i18n'
to sequelize.define('i-18-n'

and it looks like this:
```javascript
'use strict';

module.exports = (sequelize, DataTypes) => {
  var Model = sequelize.define('i-18-n', {
    id: {
      type: DataTypes.BIGINT,
      defaultValue: "nextval('i18n_id_seq')",
      allowNull: false,
      primaryKey: true
    },
  }, {
    tableName: 'i18n',
    underscored: false,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  Model.associate = (models) => {
  };

  return Model;
};
```

now everything works!

Please fix this now!

**Comment by arnaudbesnier** [comment]
@greatbody as I said in my previous message, this won't be fixed "now" but probably next week.

**Comment by jtl3d** [comment]
@arnaudbesnier awesome, thanks for the update!

**Comment by jtl3d** [comment]
@arnaudbesnier Hey just checking in on this - it's been a month since the last update. Can we expect it soon?

**Comment by arnaudbesnier** [comment]
Hey @jtl3d, The deployment of the change is progressing slowly but we really want to deliver the fix before the end of the month.
We made a few trial the past weeks, but it introduced some regressions on some projects.
We need to investigate this, to ensure nobody has issues with the new naming conventions.

**Comment by arnaudbesnier** [comment]
Hey guys, we have released all the changes we wanted to make.

It is supposed to be much more permissive right now.
No liana upgrade is necessary.
You can test it right now. Let me know if it improves your experience.

🌲🌲🌲

**Comment by jtl3d** [comment]
Unfortunately I am still seeing the issue... am I experiencing a caching issue maybe? I did a hard refresh but still get the error. I've seen some caching oddities before so maybe there is some trick I don't know.

**Comment by arnaudbesnier** [comment]
Thanks @jtl3d,
I don't think there is something to do with the cache.

So the collections that still have the issue are `CJAffiliateTransactions`, `FAQSection`, `FAQs`, `ShareASaleTransactions` right?

**Comment by jtl3d** [comment]
@arnaudbesnier Yes none of those are loading still. Basically anywhere with more than one capital letter in a row it seems. Were the changes supposed to fix these? Or were they fixing something else? Do you think you'll be able to fix these? Or should I rename them?

**Comment by jtl3d** [comment]
@arnaudbesnier any updates/insight? Should I just bite the bullet and rename my tables/models?

**Comment by arnaudbesnier** [comment]
@jtl3d let me try to reproduce your issue with the latest liana version.

**Comment by arnaudbesnier** [comment]
@jtl3d I just tried to reproduce with the latest liana version, everything works well.

here is the code to test 2 names `FAQSection` and `i18n`:

```javascript
// Sequelize migrations
module.exports = {
  up(queryInterface, Sequelize) {
    return queryInterface
      .createTable('FAQSections', {
        id: {
          type: Sequelize.INTEGER,
          primaryKey: true,
          autoIncrement: true,
        },
        createdAt: {
          type: Sequelize.DATE,
        },
        updatedAt: {
          type: Sequelize.DATE,
        },
        name: {
          type: Sequelize.STRING,
          allowNull: false,
        },
      });
  },
  down(queryInterface) {
    return queryInterface.dropTable('FAQSections');
  },
};

module.exports = {
  up(queryInterface, Sequelize) {
    return queryInterface
      .createTable('i18ns', {
        id: {
          type: Sequelize.INTEGER,
          primaryKey: true,
          autoIncrement: true,
        },
        createdAt: {
          type: Sequelize.DATE,
        },
        updatedAt: {
          type: Sequelize.DATE,
        },
        name: {
          type: Sequelize.STRING,
          allowNull: false,
        },
      });
  },
  down(queryInterface) {
    return queryInterface.dropTable('i18ns');
  },
};
```

```javascript
// Sequelize Models
module.exports = (sequelize, DataTypes) => {
  const FAQSection = sequelize.define('FAQSection', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  });

  return FAQSection;
};

module.exports = (sequelize, DataTypes) => {
  const FAQSection = sequelize.define('i18n', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  });

  return FAQSection;
};
```

**Comment by jtl3d** [comment]
Yep, newest liana fixed it. Thanks!
