### ISSUE TITLE
Searching UUID is broken

### ISSUE THREAD

**Issue by AlexisNo** [ForestAdmin/forest-express-sequelize#140]
On [this line](https://github.com/ForestAdmin/forest-express-sequelize/blob/devel/services/search-builder.js#L5), a regex should be defined, but it is a string that is created.

The result is that UUID detection tries to match the string `/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i` instead of the pattern.

Tested on node 8.4

**Comment by arnaudbesnier** [comment]
Hey @AlexisNo, thanks for the feedback. I'll try to take the time to investigate this next week.

**Comment by AlexisNo** [comment]
Any news about this ?

**Comment by arnaudbesnier** [comment]
The fix is available in the new liana version 1.5.1.

🌲🌲🌲
