### ISSUE TITLE
Extended search breaks when table contains a UUID column that is not a foreign key

### ISSUE THREAD

**Issue by AlexisNo** [ForestAdmin/forest-express-sequelize#141]
When a `UUID` attribute is declared in Sequelize, forest-express-sequelize generates a field of type `String`.

The problem is that if this field is not used a a primary or foreign key, the extended search will try to apply `lower()` on it and PostgreSQL generates this error:

```
Unexpected error: function lower(uuid) does not exist
```

**Comment by arnaudbesnier** [comment]
Hey @AlexisNo, thanks for the feedback. I'll try to take the time to investigate this next week.

**Comment by arnaudbesnier** [comment]
The fix is available in the new liana version 1.5.1.

🌲🌲🌲
