### ISSUE TITLE
Cann't custom title of belongsTo field

### ISSUE THREAD

**Issue by greatbody** [ForestAdmin/forest-express-sequelize#142]
## Expected behavior

I have two tables
One is "student", One is "school"
and I have set their relationship in
/models/student.js
```javascript
  Model.associate = (models) => {
    Model.belongsTo(models.school);
  };
```
Now I reboot server and visit http://app.forestadmin.com/xxxxxxxx/data/xxxxxx/index

What I expected is that I can custom the title of school instead of meaningless id.
## Actual behavior

I can see every student displays as a line with school displayed as a link to school detail and text is school's id.

## Failure Logs

no logs

## Context

* Package Version:1.4.5
* Express Version:4.13.4
* Sequelize Version:4.8.0
* Database Dialect:postgresql
* Database Version:PostgreSQL 9.6.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit

**Comment by arnaudbesnier** [comment]
Hi @greatbody, you can customize this value easily even though this is not yet documented in our official documentation.
 
To change the reference field of your `Schools` collection:

- Activate the edit layout editor,
- Click on the `Schools` collection settings,
- Stay on the General settings,
- Select the Reference Field you want.

It should do what you want!

I created an issue [here](https://github.com/ForestAdmin/forest-doc/issues/15) to track the documentation improvement on this feature.

**Comment by arnaudbesnier** [comment]
Hi @greatbody, did it help or do you need more info?

**Comment by greatbody** [comment]
@arnaudbesnier thanks, It does helped me.
