### ISSUE TITLE
[regression] missing timezone query parameter now breaks all "list" routes

### ISSUE THREAD

**Issue by louisremi** [ForestAdmin/forest-express-sequelize#157]
## Expected behavior

When querying the following kind of route:
`http://domain.com/forest/Model?filterType=and&filter[status]=active`
I used to be able to get all matching records.

## Actual behavior

Now my server returns a 500 with the following error:
```
Cannot read property 'format' of undefined
    at new OperatorDateIntervalParser (/home/louisremi/Workspace/cheznestor_backoffice/node_modules/forest-express-sequelize/services/operator-date-interval-parser.js:32:52)
```

## Failure Logs

The culprit seems to be this commit: 41c2768ee89aea4c8603c800d85f5d02c0c78e93
A modification of the `timezone` query param parsing has made this param mandatory

## Context

I've upgraded forest-express-sequelize from 1.5.4 to 1.5.5, and wasn't expecting to break my frontend.

**Comment by arnaudbesnier** [comment]
Hi @louisremi, thanks for the report!

Did you try to refresh the Forest frontend?

If the answer is true, and the issue still persist, would it be possible to have a screenshot of the parameters in the payload of a "list" route request to help us to investigate?
I have something in mind but I'd like to have a confirmation.

Thank you.

**Comment by louisremi** [comment]
This regression is only present in third-party apps using the REST API (e.g. our website and webhooks).
Forest itself is unaffected, as it always sends that param.

**Comment by arnaudbesnier** [comment]
Ok, then the API changed, the `timezone` parameter has to be with this format `Europe/Paris` instead of `+02:00`.

I am sorry that you were not warned of this change but honestly, we don't have the team size to manage such documentation on our API without losing some velocity.
