### ISSUE TITLE
No models directory

### ISSUE THREAD

**Issue by dragosbulugean** [ForestAdmin/forest-express-sequelize#169]
Hi,

Sorry for deleting the template, but this is a question.
How can I setup this liana if I my models are in multiple directories?
My sequelize setup requires each model and adds them to the sequelize connection.

Thanks,
Dragos

**Comment by arnaudbesnier** [comment]
Yey @dragosbulugean, you can provide directly your sequelize connection (once you models defined) like this:
```javascript
Liana.init({
  envSecret: process.env.FOREST_ENV_SECRET,
  authSecret: process.env.FOREST_AUTH_SECRET,
  sequelize: Sequelize, // Sequelize = require('sequelize');
  connections: [sequelizeConnection], // Your Sequelize connection
});
```

**Comment by dragosbulugean** [comment]
Thanks!
