### ISSUE TITLE
unable to upload UI configurations to production

### ISSUE THREAD

**Issue by NishantKhandelwal1** [ForestAdmin/forest-express-sequelize#203]
## Expected behavior

Modify UI configuration on local. It should update on production after save.

### Actual behavior

Even after getting mail production UI configuration not changed

## Context
I changed my UI configurations on local and follow all steps given in documentation but when I am trying to deploy it on production(Steps: **Copy your layout configuration** -> select production in **Copy Layout Configuration To..** -> **Copy** -> **Save changes**) it is not reflecting there.  

I got the mail of successfully deployed but unable to see changes.

* Package Version:2.12.2
* Express Version:4.15.5
* Sequelize Version:4.0.0
* Database Dialect:postgres
* Database Version:9.5

**Comment by arnaudbesnier** [comment]
Hi @NishantKhandelwal1, can you tel us the name of your Forest project to investigate this on our side? Thanks

**Comment by NishantKhandelwal1** [comment]
Hi,

Our Project name is *impact-node.*

Also another issue popped up: sometimes the UI configurations that I am
doing in development are getting lost when I refresh the browser. What
could be the possible reasons for this?

**Comment by arnaudbesnier** [comment]
@NishantKhandelwal1,
Let me close this old issue, it looks like your Forest Admin configuration is working well from what I can see.
