### ISSUE TITLE
Increase Request TimeOut

### ISSUE THREAD

**Issue by facundofarias** [ForestAdmin/forest-express-sequelize#204]
## Expected behavior

Be able to customize the request timeout when connecting to a given database (specially when using VIEWS that might take longer than a table).

## Actual behavior

On DEV environment everything works fine, but when we are using PROD, we are getting an TimeOut exception (see logs).

## Failure Logs
`
[forest] 🌳🌳🌳  Unexpected error: ResourceRequest timed out
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/xxx/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/xxx/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
`
## Context

It's running in a AWS Linux AMI, with the following versions:

* Package Version: 2.12.8
* Express Version: 4.13.4
* Sequelize Version: 4.8.0
* Database Dialect: MySQL
* Database Version: Aurora MySQL 5.6.10a

**Comment by arnaudbesnier** [comment]
Hi @facundofarias,
We won't work on such a feature this year.
Plus I am not sure this is a good idea, if a request takes more than 30 seconds to respond then the admin user experience will be really bad. So a better option would be to improve performances of the specific api endpoint.
