### ISSUE TITLE
Security - Upgrade the lodash dependency for security reasons

### ISSUE THREAD

**Issue by Jolg42** [ForestAdmin/forest-express-sequelize#220]
* Package Version: 2.16.9 forest-express-sequelize 

From `npm audit`

![screenshot 2019-01-08 at 17 38 39](https://user-images.githubusercontent.com/1328733/50845195-96dd6c00-136c-11e9-8f1c-f6a75aaabe39.png)

**Comment by arnaudbesnier** [comment]
Hi @Jolg42 ,
Thanks for the feedback.

This is now fixed in the latest beta version (`v3.0.0-beta.12`).
And should be released on "latest" in the next week 🙏
