### ISSUE TITLE
Use extended search when finding hasOne relations

### ISSUE THREAD

**Issue by smgdesign** [ForestAdmin/forest-express-sequelize#221]
When searching in an autocomplete relation field for an item I would like to be able to enable the extended search.

Is there any way of enabling this that I'm missing?

**Comment by arnaudbesnier** [comment]
Hi @smgdesign,
you cannot do that "natively" with Forest if I understand well your question.

But you can override the search route to behave the way you want.
This is some code you'll have to maintain so I would not recommend to do that, unless you have no operational workaround.
