### ISSUE TITLE
[*] Support - Does not appear to work with sequelize 5

### ISSUE THREAD

**Issue by aaronjensen** [ForestAdmin/forest-express-sequelize#226]
## Expected behavior

It should upload field information for models when using sequelize 5

## Actual behavior

It doesn't

## Failure Logs

None that I can tell

## Context

I spent over 2 hours trying to figure out why my fields were showing up with a lumber generated app but not in my own express app. Please consider adding a peerDependency to this package for sequelize in order to recommend versions that are known to work.

* Package Version: 2.17.2
* Express Version: 4.16.4
* Sequelize Version: 5.1.0
* Database Dialect: pg
* Database Version:

**Comment by arnaudbesnier** [comment]
Hi @aaronjensen,

Thanks for the feedback. We'll try to prioritize this for the coming weeks.

(Food to make the liana support Sequelize V5 here: https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md)

**Comment by arnaudbesnier** [comment]
Hi @aaronjensen,

here is the PR to support Sequelize 5:
https://github.com/ForestAdmin/forest-express-sequelize/pull/227
I'll try to finish it next week.

It should be available in the liana v3.0.0 in beta.
Thanks for your patience.

**Comment by arnaudbesnier** [comment]
@aaronjensen, the support is available in the `v3.0.0-beta.11` version and should be released in the coming weeks on the official Forest liana v3.0.0.

We already use this new beta version internally and didn't observe any issue so far.
Let us know if have any troubles using this beta version.

**Comment by aaronjensen** [comment]
Thanks!
