### ISSUE TITLE
Sequelize no longer available in Forest Admin Panel

### ISSUE THREAD

**Issue by izznogooood** [ForestAdmin/forest-express-sequelize#299]
Forest Admin seems to have dropped Sequelize, IT's no longer a choice when creating a new project in the admin panel.

**Comment by arnaudbesnier** [comment]
Hi @izznogooood ,
Indeed, now the only way to use Forest Admin is to generate an admin API micro-service (with Docker or Node.js) based on a database connection URL provided during the onboarding.
Once the micro-service generated you’ll be able to use your Forest Admin panel to manage the data from your database.
