### ISSUE TITLE
Failure to update relationship

### ISSUE THREAD

**Issue by idahogurl** [ForestAdmin/forest-express-sequelize#319]
I try to update a member's state and no changes are made.

## Expected behavior

The relationship changes to the selected value.

## Actual behavior

No changes are made.

## Context

**There are only SELECT statements no UPDATE**
![image](https://user-images.githubusercontent.com/10620169/66861424-3f4bdc80-ef4c-11e9-8284-319b2388875d.png)

**Network Panel from request is sending the right id (80 = Punjab, Pakistan)**
![image](https://user-images.githubusercontent.com/10620169/66861500-5985ba80-ef4c-11e9-9bb6-cc341d883106.png)

**Video showing steps**
https://youtu.be/uaFOvigauCg

**Zip of my Models**
https://www.icloud.com/iclouddrive/0NawNHQCPitC0cdoh91KjEWeQ#models

* Package Version: 1.4.1
* Express Version: 4.16.3
* Sequelize Version: 5.8.11
* Database Dialect: MySQL
* Database Version: 5.7.23

**Comment by arnaudbesnier** [comment]
Hi @idahogurl ,
It looks like your "states" model is badly configured.
A `state` should `belongsTo` a `country` (instead of `hasOne`) if the `countryId` foreign key is on the `states` table.
If I am right, this is not an issue of the Forest Liana, but a bad configuration on your side.

**Comment by idahogurl** [comment]
@arnaudbesnier I have tried belongsTo. Still is not working.

**Comment by idahogurl** [comment]
@arnaudbesnier The trick was that I needed to specify `foreignKey = "stateId"` and `targetKey = "id"` as well as changing to `belongsTo`. That would be good to add to your documentation.
