### ISSUE TITLE
Failure to create new item

### ISSUE THREAD

**Issue by idahogurl** [ForestAdmin/forest-express-sequelize#320]
## Expected behavior

Item is created without error

## Actual behavior

Error is given and item is not created

## Failure Logs

**Terminal Logs**
Giving Foreign Key error because I do not allow `NULL` in `country_id` in the `states` table.
![image](https://user-images.githubusercontent.com/10620169/66869597-f7818100-ef5c-11e9-90c3-dbaad7ff1c43.png)

## Context

**Network Panel is sending the id of the country**
![image](https://user-images.githubusercontent.com/10620169/66869710-2a2b7980-ef5d-11e9-9c8e-dddbb6ad24cb.png)

**Zip of my Models**
https://www.icloud.com/iclouddrive/0NawNHQCPitC0cdoh91KjEWeQ#models

**Video showing steps & error**
https://youtu.be/7JncXAoVhMI

Package Version: 1.4.1
Express Version: 4.16.3
Sequelize Version: 5.8.11
Database Dialect: MySQL
Database Version: 5.7.23

**Comment by arnaudbesnier** [comment]
Hi @idahogurl ,

It looks like your "states" model is badly configured.
A `state` should `belongsTo` a `country` (instead of `hasOne`) if the `countryId` foreign key is on the `states` table.
If I am right, this is not an issue of the Forest Liana, but a bad configuration on your side.

**Comment by idahogurl** [comment]
@arnaudbesnier I have tried belongsTo. Still is not working.

**Comment by idahogurl** [comment]
@arnaudbesnier The trick was that I needed to specify foreignKey = "stateId" and targetKey = "id" as well as changing to belongsTo. That would be good to add to your documentation.
