### ISSUE TITLE
Feature Request: Upgrade Font Awesome to v5

### ISSUE THREAD

**Issue by davidpanzarella** [ForestAdmin/forest-express-sequelize#367]
Not an issue, but it'd be nice to have more contextual options for font choices for models. Font Awesome 5 has a lot more options than previous ones. Is it possible to update it? Or if you guys are using 5, maybe add more icons or the ability to upload your own custom ones?

**Comment by rap2hpoutre** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fontwaesome 5](https://trello.com/c/N4tfe0sV/2211-fontwaesome-5)

**Comment by rap2hpoutre** [comment]
Hi @davidpanzarella. Thank you for your feedback! :pray: 

I created a card in our triage board to consider your suggestion. 🚀 

I take the liberty of closing this issue: it does not belongs to forest-express-sequelize package itself (it's more a ForestAdmin feature request). Let me know if you need more feedback!
