### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by pierrelaburthe** [ForestAdmin/forest-express-sequelize#499]
Hello, I am trying to set up Forest Admin using the NPM method, and it seems broken. 

Here is what I have : 
➜  ~ npm install -g lumber-cli@latest -s                                                                                                                                                                                            [(2.6.3)]

/usr/local/bin/lumber -> /usr/local/lib/node_modules/lumber-cli/lumber.js
+ lumber-cli@3.6.8
added 217 packages from 344 contributors in 31.159s

➜  ~ lumber generate “Logora-off” --connection-url “postgres://XXXXX:XXXXXX%XXXXX@localhost:5432/ebdb” --ssl true --schema “public” --application-host “localhost” --application-port “3310" --email “pierre@XXXXX.fr” --token “XXXXXXXXXXXXXXX" && cd “Logora-off” && npm install -s
? What's your email address?  pierre@XXXXX.fr
> Cannot generate your project.
> An unexpected error occurred. Please reach out for help in our Developers community (https://community.forestadmin.com/) or create a Github issue with following error: TypeError: Cannot read property 'replace' of null

**Comment by arnaudbesnier** [comment]
Hi @pierrelaburthe,
I think you made a mistake about you host during the configuration step.

I edited your initial post to remove the sensitive database credentials you exposed publicly.

Can you contact me in PM in our [community forum](https://community.forestadmin.com/u/arnaud/summary) to let me share your well formatted database url?

**Comment by arnaudbesnier** [comment]
Credentials mistake confirmed.
Solved in PM.
