### ISSUE TITLE
"column does not exist" after upgrade to 3.6.8

### ISSUE THREAD

**Issue by znarf** [ForestAdmin/forest-express-sequelize#503]
## Expected behavior

No error

## Actual behavior

After upgrading from 3.6.6 to 3.6.8, our Forest integration is suddenly broken, with the following error:

## Failure Logs

```
 [forest] 🌳🌳🌳  Unexpected error: column User.fullname does not exist

SequelizeDatabaseError: column User.fullname does not exist
  at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
  at /app/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
  at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
  at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
  at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
  at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
  at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
  at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
  at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
  at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
  at processImmediate (internal/timers.js:439:21)
  at process.topLevelDomainCallback (domain.js:131:23)
```

## Context

In our case, "fullname" is not a real column but defined with the following code:

```
Liana.collection('User', {
  fields: [
    {
      field: 'fullname',
      type: 'String',
      get: object => {
        return `${object.firstName || ''} ${object.lastName || ''}`.trim();
      },
    },
  ],
});
```

* Package Version: 3.6.8
* Express Version: 4.17.1
* Sequelize Version: 5.22.3
* Database Dialect: Postgresql
* Database Version: 9.6.18

**Comment by arnaud-moncel** [comment]
Hi @znarf 👋  Thank you to your feedback.
We currently try to reproduce your issue.
If you want, you can follow the [discussion](https://community.forestadmin.com/t/latest-forest-express-sequelize-breaks-smart-fields/897) on our forum.
I will keep you update.

**Comment by znarf** [comment]
@arnaud-moncel could it be that our schema is not up to date?

**Comment by arnaud-moncel** [comment]
Maybe a miss configuration of this field ?

Can you try to find in your `.forestadmin-schema.json` the declaration of your field?
```
 {
      "field": "fullName",
      "type": "String",
      "defaultValue": null,
      "enums": null,
      "integration": null,
      "isFilterable": false,
      "isReadOnly": true,
      "isRequired": false,
      "isSortable": false,
      "isVirtual": true,
      "reference": null,
      "inverseOf": null,
      "validations": []
 }
```
And see if `isVirtual` is set to true.

**Comment by znarf** [comment]
Looks good:
https://github.com/opencollective/opencollective-api/blob/master/.forestadmin-schema.json

```
        {
          "field": "fullname",
          "type": "String",
          "defaultValue": null,
          "enums": null,
          "integration": null,
          "isFilterable": false,
          "isReadOnly": true,
          "isRequired": false,
          "isSortable": false,
          "isVirtual": true,
          "reference": null,
          "inverseOf": null,
          "validations": []
        },
```

**Comment by arnaud-moncel** [comment]
What is your project name please ? I will take a look about configuration on our end.

**Comment by znarf** [comment]
@arnaud-moncel "Open Collective.1"

**Comment by arnaudbesnier** [comment]
Hi @znarf,

We reproduced the issue.
The team is currently working on a fix.

If you need a safe spot, you should definitively downgrade your `forest-express-sequelize` package version to `v6.3.6`.
We’ll let you know once a new patch version is available.

Thanks for your patience.

**Comment by ghusse** [comment]
@znarf can you try the latest version `6.3.10` which contains the fix for your issue?

**Comment by znarf** [comment]
@ghusse it's on its way https://github.com/opencollective/opencollective-api/pull/4527, will update you when it's live.

**Comment by znarf** [comment]
All good!
