### ISSUE TITLE
Updating a smart collection's fields isn't manifesting on UI.

### ISSUE THREAD

**Issue by landerton** [ForestAdmin/forest-express-sequelize#62]
I've created a smart collection that shows in my admin UI. After adding a few more fields and removing some, nothing changes on the admin UI. Still showing the original fields I created.

**Comment by arnaudbesnier** [comment]
hey @landerton, you're right it should!
Did you restart your server after applying the changes in your smart collection?

**Comment by landerton** [comment]
Yes restarted many times. This was in a development environment, if that helps.

**Comment by arnaudbesnier** [comment]
@landerton We didn't find a way to reproduce your issue. Can you provide a specific example of field update or removal?

**Comment by arnaudbesnier** [comment]
@landerton we didn't receive news about your issue. I close this issue.
We would be happy to help you in the future if your issue persists.
