### ISSUE TITLE
Using smart fields to convert postgresql POINT GEOMETRY to string

### ISSUE THREAD

**Issue by HarrisRobin** [ForestAdmin/forest-express-sequelize#66]
Hi,

Trying to use http://doc.forestadmin.com/developers-guide/#smart-field to allow myself to edit postgresql geometry fields in forest admin, specifically the points type as shown [here](https://www.postgresql.org/docs/9.5/static/datatype-geometric.html), however I can't seem to get it to work.

Steps: 
I attempted the following code:
```js
Liana.collection('Job', {
  fields: [{
    field: 'location',
    type: 'String',
    value: function(object) {
      console.log('object Liana', object)
      return object.latitude + ', ' + object.longitude
    }
  }]
})
```
At this point, I am getting the following error:
```
[forest] 🌳🌳🌳  Cannot customize your collection named "Job" properly. Did you call the "collection" method in the /forest directory?
```

My table is called `Job` but in forest it's showing as `Jobs`. I attempted both `Job` and `Jobs` with no luck and the same error above.

Couldn't get this to work, any help is appreciated :)

**Comment by arnaudbesnier** [comment]
Hey @HarrisRobin, where is located the file containing the code? Did you create a /forest directory at the root of your project?

**Comment by HarrisRobin** [comment]
@arnaudbesnier i did not! I am using the middleware and so far have had no need to create a /forest directory. 

My structure looks like this (i am using [feathersjs](http://feathersjs.com/)) 
```
src 
-- app.js
-- models
    -- index.js
```

The code is located in app.js, here is a gist 
https://gist.github.com/HarrisRobin/d7351dd8896aa70b490435f4c561d11c

**Comment by arnaudbesnier** [comment]
Yes but you need to. If you don't create a file like `/forest/job.js` le liana won't read the smart field you created. Sorry, it is not really clear in the documentation.

**Comment by HarrisRobin** [comment]
Thank you Arnaud, will attempt this when I get in front of my laptop! Do
you have an example by any chance?

Thanks again for the fast responses

**Comment by HarrisRobin** [comment]
Hi @arnaudbesnier this issue still persists for me. Any chance I can get some help? I re-read the documentation and do I have to create a `smart collection` for the `smart field` to work? Was hoping to avoid doing that if it's just to add a simple field like location but if that's what's needed I'll give it a try!

Thanks

**Comment by arnaudbesnier** [comment]
@HarrisRobin is 'location' also the name of your point geometry field in your model?

**Comment by HarrisRobin** [comment]
@arnaudbesnier yes that's right!

**Comment by arnaudbesnier** [comment]
@HarrisRobin then you should try another name, I think it should work.
No doubt, we can consider the behaviour you described as a bug, so the workaround is to find another name for your Smart Field and it should appear in the UI.

**Comment by HarrisRobin** [comment]
@arnaudbesnier thank you for the follow up! What you said worked, however the field itself is read-only in forestadmin's UI:
<img width="543" alt="screenshot 2017-02-11 18 02 04" src="https://cloud.githubusercontent.com/assets/3880008/22858208/3842e560-f084-11e6-8668-188ca03f7a86.png">

Also, I remember being told there was a map widget so was wondering how that would work.

Thanks a lot :)

**Comment by arnaudbesnier** [comment]
@HarrisRobin Smart Field are read only right now, but we definitely want to implement the feature to make them writable. It should be implemented within a month or 2.

About widgets, we really need to improve our documentation but you can take a look in your Collection Settings > Fields > Custom Location field > Widget. To display your collection settings, you just have to activate the "Edit Layout" switch.

**Comment by HarrisRobin** [comment]
@arnaudbesnier got it. looking forward for the feature as it's important for us to be able to define location right now :)

I think this can be closed now. Thanks for your help @arnaudbesnier !
