### ISSUE TITLE
Text area widgets do not respond to 'read-only'

### ISSUE THREAD

**Issue by jeremyjaybaker** [ForestAdmin/forest-express-sequelize#69]
My use case: I had an editable text area for a model, but for UX reasons, I changed my mind and decided to mark it as read-only.

Reproduction steps:
- Edit the fields of any model
- Set a field's type to 'text-area' and check 'read-only'
- Save and refresh the page
- Open the edit or new form of the model. The attribute can still be written to.

**Comment by arnaudbesnier** [comment]
@jeremyjaybaker thanks for the feedback, you're right about this issue.
We are working on a brand new design branch, I just tried to reproduce the issue and I confirm that this is fixed in the new design.

You'll have to wait 2 or 3 weeks to have this new version... sorry for that.

**Comment by arnaudbesnier** [comment]
hi @jeremyjaybaker, the new Forest design has been released yesterday. This issue is now fixed, then.

Enjoy the new 🌲 Forest 🌲

**Comment by jeremyjaybaker** [comment]
@arnaudbesnier thank you! :)
