### ISSUE TITLE
Cannot modify a file once it is uploaded

### ISSUE THREAD

**Issue by jeremyjaybaker** [ForestAdmin/forest-express-sequelize#70]
I'm not sure if this is intentional or not, but it appears that uploaded images cannot be modified once they have been uploaded? Here's a screenshot from my dashboard where I'm attempting to edit an existing model with an image: 
![edit_image](https://cloud.githubusercontent.com/assets/6502108/22842389/0a4e7a2a-efa3-11e6-99dd-4eae603f9087.png)

**Comment by arnaudbesnier** [comment]
@jeremyjaybaker images can be modified. You can edit your record by clicking on the small grey pencil close to the record name (at the top of the screenshot). Once in "edit mode" you'll be able to choose a new picture for the current record.

**Comment by enxtur** [comment]
i clicked small grey pencil && still unable upload new picture :)
![Image of Yaktocat](http://imgh.us/Screen_Shot_2017-03-23_at_5.49.57_PM.png)

**Comment by jeremyjaybaker** [comment]
@arnaudbesnier Thanks! Not sure if this was just an old dashboard issue or I just missed something, but it works just fine now.
