### ISSUE TITLE
Field Type: Support DATEONLY column type

### ISSUE THREAD

**Issue by Slind14** [ForestAdmin/forest-express-sequelize#74]
Hi there,
the support for DATEONLY is missing. While it is easy to be added, the Forest UI needs to support it. While the normal date picker can be used, it is very difficult to set a date that is +10 years into the past or future.

**Comment by arnaudbesnier** [comment]
Hi @Slind14 the Dateonly support feature is currently in review by the team, we'll let you know once a new package version is available.

🌲🌲🌲

**Comment by arnaudbesnier** [comment]
Hey @Slind14, this feature is released in the new liana version 1.0.10.
Enjoy!

🌲🌲🌲

**Comment by Slind14** [comment]
Thanks
