### ISSUE TITLE
Issues caused by User class not having id as the primary key

### ISSUE THREAD

**Issue by jeremyjaybaker** [ForestAdmin/forest-express-sequelize#80]
The User class on one of our apps uses a primary key called 'uuid' instead of 'id'. I assume that Forest expects an 'id' column by default because the default Dashboard tab throws this exception every time the Dashboard is accessed:
``PG::UndefinedColumn: ERROR:  column "id" does not exist
LINE 1: SELECT DISTINCT COUNT(DISTINCT id) FROM "users" LEFT OUTER J...
                                      ^
: SELECT DISTINCT COUNT(DISTINCT id) FROM "users" LEFT OUTER JOIN "users" "primary_accounts_users" ON "primary_accounts_users"."uuid" = "users"."primary_account_id"``

This is also preventing us from deleting users. Is there a way to change the default primary key name that forest expects?

**Comment by arnaudbesnier** [comment]
Hi @jeremyjaybaker, thanks for the report!
There is no such a current feature. The Forest liana should be smart enough to detect the right primary key. This is definitely an issue. We will try to fix this soon.

**Comment by arnaudbesnier** [comment]
Hi @jeremyjaybaker, I was wrong, this is currently supported by the current liana version. I didn't manage to reproduce your issue creating a table with a `name` column as primary key. Everything seems to work fine (create, update, delete, list,...).

Here is my test migration and model:
’’’
// Migration
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface
      .createTable('cars', {
        name: { type: Sequelize.STRING, primaryKey: true },
        speed: { type: Sequelize.INTEGER },
        createdAt: { type: Sequelize.DATE },
        updatedAt: { type: Sequelize.DATE },
        deletedAt: { type: Sequelize.DATE }
      });
  },
  down: function (queryInterface) {
    return queryInterface.dropTable('cars');
  }
};

// Model
module.exports = function (sequelize, DataTypes) {
  var models = sequelize.models;

  var Car = sequelize.define('car', {
    name: { type: DataTypes.STRING, primaryKey: true },
    speed: { type: DataTypes.INTEGER }
  }, {
    paranoid: true
  });

  Car.removeAttribute('id');

  return Car;
};


’’’

What was the action you did to generate such an error?

**Comment by jeremyjaybaker** [comment]
I am not sure how this ended up getting reported on the forest-express-sequelize repo. This is rather embarrassing, but I think I submitted the issue to the wrong repo. Apologies for the time you've spent so far looking into this. The issue was intended to be reported on https://github.com/ForestAdmin/forest-rails. Should I go ahead and move this over to the other repo myself @arnaudbesnier?

**Comment by arnaudbesnier** [comment]
@jeremyjaybaker, no problem.
Yes, can you please create the same issue on the Rails repository? Thank you.
