### ISSUE TITLE
Smart field example - fullName - doesn't work

### ISSUE THREAD

**Issue by tylercollier** [ForestAdmin/forest-express-sequelize#87]
I'm using forest-express-sequelize@1.0.11 although I had forest-express-sequelize@0.5.4 earlier today and it's the same problem I think.

I got this example from [your website on Smart Fields](http://doc.forestadmin.com/developers-guide/):

```
// /forest/user.js
'use strict';
var Liana = require('forest-express-sequelize');

Liana.collection('user', {
  fields: [{
    field: 'fullname',
    type: 'String',
    value: function (object) {
      return object.firstName + ' ' + object.lastName;
    }
  }]
});
```

**What I did:**

First, I used the Layout editor to change the User table. For "When a user is referenced, I want to see the field…", I chose fullName. I had created the `forest/user.js` field as instructed.

I used the Forest Admin website to create a new record. I was creating a Credit Check record, which belongs to Users. I put my cursor in the User textbox and started typing a name.

**What I expected to happen:**

The list of auto-suggested values to give full names of users from the Users table.

**What I actually saw happen:**

Each name showed `undefined undefined`. If I log `object`, I can see it's a Sequelize object whose only value is `{ id: 1 }`, which would explain it. So it has no values besides id, thus `object.firstName + ' ' + object.lastName` would be `undefined undefined`.

My question is why do the Sequelize records only have the id field? Why don't they have all fields?

**Other hints:**

In the table view of Credit Checks, the "user" field sometimes shows the email address (no idea how it picked that field), sometimes it shows "undefined undefined".

In the detail view, the "user" field sometimes shows the user's ID, e.g. 1.

**Comment by tylercollier** [comment]
The full name smart field works fine when viewing the Users table.

And, sometimes when I look at the Credit Checks table, the User field shows a full name. Other times it shows `undefined undefined. Why does it show the right thing sometimes?

**Comment by SeyZ** [comment]
Hey @tylercollier Thank you for your issue (and for your email).  

Let me try to reproduce this issue on my side and fix it from next week (our next sprint). I'll keep you posted!

**Comment by arnaudbesnier** [comment]
Hi @tylercollier, we have made a lot of bug fixes and improvements this month to remove all the unexpected things:

- while typing a User name in the user field of a Credit Check record, now, you should *always see the fullName value* displayed in the list of found Users (or the User id as the default value if the fullName cannot be computed),
- now, the records returned from a search contain *all the attributes*,
- email value will never be a used anymore in the reference field default value (unless you select this field as the reference field for your collections)

The only thing to do is to update your Express-Sequelize liana to the latest version:
https://github.com/ForestAdmin/forest-express-sequelize/blob/devel/CHANGELOG.md#release-113---2017-05-24

One last thing, about your current implementation of the Smart Field, is that if the `firstName` and `lastName` does not exist for the current User record the Smart Field value will be "undefined undefined".

To prevent this behavior, you should implement your Smart Field this way:
```javascript
// /forest/user.js
'use strict';
var Liana = require('forest-express-sequelize');

Liana.collection('user', {
  fields: [{
    field: 'fullname',
    type: 'String',
    value: function (object) {
      if (object.firstName && object.lastName) {
        return object.firstName + ' ' + object.lastName;
      } else {
        return null;
      }
    }
  }]
});
```

I am really confident that all your issues will be solved. Let us know!

🌲🌲🌲

**Comment by tylercollier** [comment]
I upgraded to 1.1.3 and it works now! Thanks for addressing all my concerns from my post!

1. FYI, the first smart field example from the [developer's guide](http://doc.forestadmin.com/developers-guide/#smart-fields) does not have the `else return null` clause.
1. How would returning null help? Does it show the record ID in that case?

**Comment by arnaudbesnier** [comment]
🎉 

For the first point, you're right. I added a task to update the documentation for a better implementation of the fullName Smart Field (`else return null`).

About the second point, yes if the Smart Field *used as the reference field* does not have a value (`null` value), the UI fallbacks to the id/primary key.
