### ISSUE TITLE
Smart Action Not Rendering Button And Breaking UI

### ISSUE THREAD

**Issue by evanmrose** [ForestAdmin/forest-express-sequelize#91]
Here is the code in my forest/user.js
````
var Liana = require('forest-express-sequelize');
console.log('liana object', Liana);

Liana.collection('user', {
  actions: [
    {
      name: 'Test Add Admin User',
      fields: [
        {
          field: 'First Name',
          type: 'String'
        }
      ]
    }
  ]
});
````

It causes wonky rendering across the Forest Admin UI but no smart action button to use.

<img width="879" alt="screen shot 2017-05-07 at 9 20 10 pm" src="https://cloud.githubusercontent.com/assets/833570/25786990/32605e32-336b-11e7-954b-0e7631c1ac5f.png">
<img width="308" alt="screen shot 2017-05-07 at 9 20 03 pm" src="https://cloud.githubusercontent.com/assets/833570/25786988/325eeae8-336b-11e7-8e54-eb17a7eae688.png">
<img width="1129" alt="screen shot 2017-05-07 at 9 19 47 pm" src="https://cloud.githubusercontent.com/assets/833570/25786989/325f2ec2-336b-11e7-8732-07d112209c99.png">
<img width="1392" alt="screen shot 2017-05-07 at 9 19 32 pm" src="https://cloud.githubusercontent.com/assets/833570/25786991/3260eb4a-336b-11e7-9820-0a88a4f1ea98.png">

**Comment by evanmrose** [comment]
This is in my local environment by the way.

**Comment by evanmrose** [comment]
Traced the action object through the Liana.collections function call and here is what came out:

Cliff notes, the action gets added to Schemas.schemas['User'].actions but it just isn't getting rendered by the Forest Admin UI.

````
collection in forest express { name: 'User',
  idField: 'id',
  fields:
   [ { field: 'id', type: 'Number', columnName: 'id' },
     { field: 'email', type: 'String', columnName: 'email' },
     { field: 'passwordHash',
       type: 'String',
       columnName: 'passwordHash' },
     { field: 'firstName', type: 'String', columnName: 'firstName' },
     { field: 'lastName', type: 'String', columnName: 'lastName' },
     { field: 'middleName', type: 'String', columnName: 'middleName' },
     { field: 'valid', type: 'Boolean', columnName: 'valid' },
     { field: 'disabled', type: 'Boolean', columnName: 'disabled' },
     { field: 'jurisdictionId',
       type: 'Number',
       columnName: 'jurisdictionId' },
     { field: 'createdAt', type: 'Date', columnName: 'createdAt' },
     { field: 'updatedAt', type: 'Date', columnName: 'updatedAt' },
     { field: 'Role',
       type: 'Number',
       reference: 'Role.roleId',
       inverseOf: null },
     { field: 'State',
       type: 'Number',
       reference: 'State.stateId',
       inverseOf: null },
     { field: 'Searches',
       type: [Object],
       reference: 'Search.userId',
       inverseOf: null },
     { field: 'Grants',
       type: [Object],
       reference: 'Grant.grantorId',
       inverseOf: null },
     { field: 'Campaigns',
       type: [Object],
       reference: 'Campaign.userId',
       inverseOf: null },
     { field: 'Reports',
       type: [Object],
       reference: 'Report.generatedById',
       inverseOf: null },
     { field: 'invitee',
       type: [Object],
       reference: 'User.inviterId',
       inverseOf: null },
     { field: 'inviter',
       type: 'Number',
       reference: 'User.inviterId',
       inverseOf: null },
     { field: 'defaultAreas',
       type: [Object],
       reference: 'Area.userId',
       inverseOf: null } ] }
````
````
actions are [ { name: 'RegisterAdmin',
    fields: [ [Object] ],
    id: 'User.RegisterAdmin' } ]
````

````
schema actions after merge [ { name: 'RegisterAdmin',
    fields: [ [Object] ],
    id: 'User.RegisterAdmin' } ]
````

**Comment by SeyZ** [comment]
hey @evanmrose thanks for report! This is a very strange behavior. It's possible to have a delay to see your action in the admin but it should not crash your UI! Do you have an error in your chrome console to share when accessing the user collection?

Thanks!

**Comment by evanmrose** [comment]
Seems this was resolved with time. That said, there is still some wonkiness going on. The only field I have defined is firstName but here is what I see in my custom action:
<img width="680" alt="screen shot 2017-05-08 at 9 40 47 am" src="https://cloud.githubusercontent.com/assets/833570/25808454/26c66ee6-33d8-11e7-8861-8a0b3017d746.png">

What is the update process for this? I thought it would be immediate when I committed but is there some amount of time I need to wait to see updates?

Separately, on the handling side, I am getting `2017-05-08T13:36:35.895Z - error:  name=Unauthorized, status=401, message=Bad JWT token.` when calling `liana.ensureAuthenticated`

**Comment by evanmrose** [comment]
Spoke too soon. I changed the action name from RegisterAdmin to Register Admin and this is what I see now:
<img width="1133" alt="screen shot 2017-05-08 at 1 03 16 pm" src="https://cloud.githubusercontent.com/assets/833570/25815535/e0b1c8b2-33ee-11e7-808b-72831579697c.png">

I'm guessing the way you guys do Ids by concatenating collection.action breaks when there's a space in the id? @SeyZ

**Comment by evanmrose** [comment]
Console Logs:
<img width="759" alt="screen shot 2017-05-08 at 5 54 18 pm" src="https://cloud.githubusercontent.com/assets/833570/25827091/7b427a34-3417-11e7-94a6-abbcd07de1be.png">
<img width="735" alt="screen shot 2017-05-08 at 4 46 58 pm" src="https://cloud.githubusercontent.com/assets/833570/25827090/7b410500-3417-11e7-93e2-a14fd5e7bd9e.png">

**Comment by SeyZ** [comment]
@evanmrose Thanks for all your messages. I think it would be more efficient to schedule a quick call to review all your points and to fix them ;) Please, send me an email to sandro@forestadmin.com :)

**Comment by evanmrose** [comment]
hey @SeyZ shot you a couple of emails but looks like we missed eachother. Any way we can connect next week?

**Comment by arnaudbesnier** [comment]
Hi @evanmrose, Did you eventually manage to have your Smart Actions rendered properly?

**Comment by angelstoone** [comment]
Hi everyone, after having the problem that I wrote in #119, I tried to create a new project and I put the new FOREST_ENV_SECRET and FOREST_AUTH_SECRET in the project code. Now in the newly created project, I am getting this issue as well, just on one table.
