### ISSUE TITLE
How to configure this for local environment?

### ISSUE THREAD

**Issue by AndrejGajdos** [ForestAdmin/forest-express-sequelize#996]
If I try to use this package for my local environment, I am getting `404` for `/forest/authentication route`.

<img width="1100" alt="Screenshot 2022-08-16 at 10 59 32" src="https://user-images.githubusercontent.com/1593758/184840577-ba8f3db6-a32c-4553-9a54-6d15a5245530.png">

I create basic [repo](https://github.com/AndrejGajdos/forest_test) project to reproduce the issue.

**Comment by Scra3** [comment]
Hello,
Thanks you for the issue.
Could you please create a report to our [forum](https://community.forestadmin.com/) please. 🙏

**Comment by AndrejGajdos** [comment]
I think there is no need for that, because I am using the new agent instead of [forest-express-sequelize](https://github.com/ForestAdmin/forest-express-sequelize)

**Comment by Scra3** [comment]
Nice, welcome to the new agent :)
